#!/usr/bin/env python3
"""
generate-book.py — Build a book for the Atlas Books / Star Federation platform

Source directory (books-source/<name>/):
  config.json              — metadata + TTS settings
  book.md                  — content (primary format)
  cover.jpg / cover.png    — cover image (also: book.jpg / book.png)

Output directory (books-dest/<name>/):
  <name>.html              — self-contained viewer (template + book data)
  <name>.epub              — e-reader format  (--epub)
  <name>.pdf               — print document   (--pdf)
  <name>-<chapter>.mp3    — TTS audio per chapter (generated by default)

Usage:
  python tools/generate-book.py --input star-federation
  python tools/generate-book.py --input star-federation --epub --pdf
  python tools/generate-book.py --input star-federation --no-tts
  python tools/generate-book.py --all
  python tools/generate-book.py --list

config.json example:
  {
    "id": "star-federation",
    "title": "Star Federation",
    "author": "Arkadiusz Klemenko",
    "year": "2026",
    "lang": "pl",
    "description": "...",
    "published": false,
    "tts": {
      "voice": "pl-PL-MarekNeural",
      "rate": "+0%",
      "pitch": "+0Hz"
    }
  }
"""

from __future__ import annotations
import argparse, asyncio, base64, json, re, sys
from html import escape
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────────
SCRIPT_DIR    = Path(__file__).parent
PROJECT_DIR   = SCRIPT_DIR.parent
BOOK_SOURCE   = PROJECT_DIR / "books-source"
BOOK_DEST     = PROJECT_DIR / "books-dest"
PUBLIC_DIR    = PROJECT_DIR / "public"
TEMPLATE_PATH = PUBLIC_DIR / "book-template.html"

# ── ANSI colour helpers ────────────────────────────────────────────────────────
def _c(code: str, t: str) -> str:
    return f"\033[{code}m{t}\033[0m" if sys.stdout.isatty() else t

def gold(t: str)  -> str: return _c("33", t)
def green(t: str) -> str: return _c("32", t)
def red(t: str)   -> str: return _c("31", t)
def gray(t: str)  -> str: return _c("90", t)
def cyan(t: str)  -> str: return _c("36", t)
def bold(t: str)  -> str: return _c("1",  t)
def dim(t: str)   -> str: return _c("2",  t)

def ok(msg: str)   -> None: print(f"  {green('✓')} {msg}")
def err(msg: str)  -> None: print(f"  {red('✗')} {msg}")
def info(msg: str) -> None: print(f"  {gold('·')} {msg}")
def step(msg: str) -> None: print(f"\n  {bold(gold('▶'))} {msg}")

# ── Help ───────────────────────────────────────────────────────────────────────
def print_help() -> None:
    print()
    print(f"  {gold(bold('★ ATLAS BOOKS — GENERATE'))}   {dim('tools/generate-book.py')}")
    print()
    print(f"  {bold('USAGE')}")
    def cmd(s: str, c: str = "") -> None:
        suffix = f"  {gray('# ' + c)}" if c else ""
        print(f"    {cyan(s)}{suffix}")
    cmd("python tools/generate-book.py --list",                       "list all books in books-source/")
    cmd("python tools/generate-book.py --input star-federation",      "build HTML + MP3 + EPUB + PDF")
    cmd("python tools/generate-book.py --input star-federation --no-tts",    "skip TTS audio")
    cmd("python tools/generate-book.py --input star-federation --no-epub --no-pdf", "HTML + MP3 only")
    cmd("python tools/generate-book.py --all",                        "generate all books")
    print()
    print(f"  {bold('FLAGS')}")
    cmd("--no-tts",             "skip MP3 audio generation")
    cmd("--no-epub",            "skip EPUB generation")
    cmd("--no-pdf",             "skip PDF generation  (requires: pip install weasyprint)")
    cmd("--tts-voice <voice>",  "override TTS voice (default from config.json)")
    cmd("--tts-rate <+0%>",     "speech rate")
    cmd("--tts-pitch <+0Hz>",   "speech pitch")
    print()
    print(f"  {bold('TTS')}")
    print(f"    Requires: {cyan('pip install edge-tts')}")
    print()
    def voice(short: str, gender: str, locale: str, tags: str) -> None:
        g = "♀" if gender == "Female" else "♂"
        print(f"    {cyan(short):<42} {g}  {dim(tags)}")
    print(f"  {bold('  pl-PL')}")
    voice("pl-PL-ZofiaNeural",       "Female", "pl-PL", "Friendly, Positive")
    voice("pl-PL-MarekNeural",       "Male",   "pl-PL", "Friendly, Positive")
    print()
    print(f"  {bold('  en-US')}")
    voice("en-US-AriaNeural",        "Female", "en-US", "Positive, Confident  [News, Novel]")
    voice("en-US-JennyNeural",       "Female", "en-US", "Friendly, Considerate  [Conversation, News]")
    voice("en-US-MichelleNeural",    "Female", "en-US", "Friendly, Pleasant  [News, Novel]")
    voice("en-US-AnaNeural",         "Female", "en-US", "Cute  [Cartoon, Conversation]")
    voice("en-US-ChristopherNeural", "Male",   "en-US", "Reliable, Authority  [News, Novel]")
    voice("en-US-EricNeural",        "Male",   "en-US", "Rational  [News, Novel]")
    voice("en-US-GuyNeural",         "Male",   "en-US", "Passion  [News, Novel]")
    voice("en-US-RogerNeural",       "Male",   "en-US", "Lively  [News, Novel]")
    voice("en-US-SteffanNeural",     "Male",   "en-US", "Rational  [News, Novel]")
    print()
    print(f"  {bold('  en-GB')}")
    voice("en-GB-LibbyNeural",       "Female", "en-GB", "Friendly, Positive")
    voice("en-GB-MaisieNeural",      "Female", "en-GB", "Friendly, Positive")
    voice("en-GB-SoniaNeural",       "Female", "en-GB", "Friendly, Positive")
    voice("en-GB-RyanNeural",        "Male",   "en-GB", "Friendly, Positive")
    voice("en-GB-ThomasNeural",      "Male",   "en-GB", "Friendly, Positive")
    print()
    print(f"  {bold('DIRECTORIES')}")
    cmd("books-source/<name>/",  "source: config.json + book.md + cover.jpg")
    cmd("books-dest/<name>/",    "output: .html + .epub + .pdf + .mp3 files")
    cmd("public/",              "deploy: run publish-book.py to copy here")
    print()

# ── Config ─────────────────────────────────────────────────────────────────────
def load_config(book_dir: Path) -> dict:
    cfg_path = book_dir / "config.json"
    if not cfg_path.exists():
        raise FileNotFoundError(f"Missing config.json in {book_dir}")
    return json.loads(cfg_path.read_text(encoding="utf-8"))

def save_config(book_dir: Path, config: dict) -> None:
    cfg_path = book_dir / "config.json"
    cfg_path.write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8")

# ── Cover ──────────────────────────────────────────────────────────────────────
COVER_NAMES = ["cover.jpg", "cover.png", "book.jpg", "book.png"]

def load_cover_b64(book_dir: Path) -> str:
    for name in COVER_NAMES:
        p = book_dir / name
        if p.exists():
            mime = "image/jpeg" if p.suffix.lower() in (".jpg", ".jpeg") else "image/png"
            data = base64.b64encode(p.read_bytes()).decode()
            info(f"Cover: {name} ({p.stat().st_size // 1024} kB)")
            return f"data:{mime};base64,{data}"
    return ""

# ── Markdown parser ────────────────────────────────────────────────────────────
def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_-]+', '-', text)
    return re.sub(r'^-+|-+$', '', text) or 'chapter'

def _strip_inline(text: str) -> str:
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'_(.+?)_', r'\1', text)
    text = re.sub(r'`(.+?)`', r'\1', text)
    return text.strip()

def parse_markdown(content: str) -> tuple[dict, list[dict]]:
    """Parse markdown → (front_matter_meta, chapters_list)."""
    raw_lines = content.splitlines()

    # Front matter
    meta: dict = {}
    lines = raw_lines
    if lines and lines[0].strip() == '---':
        i = 1
        while i < len(lines) and lines[i].strip() != '---':
            if ':' in lines[i]:
                key, _, val = lines[i].partition(':')
                meta[key.strip()] = val.strip()
            i += 1
        lines = lines[i + 1:]

    chapters: list[dict] = []
    current: dict | None = None
    chapter_num = 0
    chapter_subtitle_set = False
    skip_next = False
    in_quote: list[str] = []

    def flush_quote():
        nonlocal in_quote
        if in_quote and current is not None:
            texts, attr = [], None
            for ql in in_quote:
                content_q = re.sub(r'^>\s?', '', ql)
                m = re.match(r'^[—–-]\s*(.+)', content_q.strip())
                if m:
                    attr = m.group(1).strip()
                else:
                    texts.append(content_q)
            block: dict = {'type': 'quote', 'text': ' '.join(t for t in texts if t).strip()}
            if attr:
                block['attribution'] = attr
            current['blocks'].append(block)
        in_quote = []

    i = 0
    while i < len(lines):
        if skip_next:
            skip_next = False
            i += 1
            continue

        line  = lines[i]
        strip = line.strip()

        # Verse fence
        if strip.startswith('```verse'):
            flush_quote()
            i += 1
            verse_lines = []
            while i < len(lines) and not lines[i].strip().startswith('```'):
                verse_lines.append(lines[i].rstrip())
                i += 1
            i += 1
            if current is not None:
                current['blocks'].append({'type': 'verse', 'text': '\n'.join(verse_lines)})
            continue

        # Callout :::
        if re.match(r'^:::', strip):
            flush_quote()
            m = re.match(r'^:::\s*(\S+)\s*(.*)', strip)
            if m:
                label = m.group(1)
                title_label = m.group(2).strip()
                call_lines = []
                i += 1
                while i < len(lines) and not lines[i].strip().startswith(':::'):
                    call_lines.append(lines[i].rstrip())
                    i += 1
                text = '\n'.join(call_lines).strip()
                block = {'type': 'callout', 'text': text}
                if title_label:
                    block['label'] = title_label
                elif label != 'callout':
                    block['label'] = label
                if current is not None:
                    current['blocks'].append(block)
            i += 1
            continue

        # Blockquote
        if strip.startswith('>'):
            in_quote.append(line)
            i += 1
            continue
        elif in_quote:
            flush_quote()

        # Divider
        if re.match(r'^[-*_]{3,}$', strip):
            if current is not None:
                current['blocks'].append({'type': 'divider'})
            i += 1
            continue

        # H1 = new chapter
        if strip.startswith('# ') and not strip.startswith('## '):
            if current is not None:
                chapters.append(current)
            chapter_num += 1
            title = _strip_inline(strip[2:])
            current = {'id': slugify(title), 'number': chapter_num, 'title': title, 'blocks': []}
            chapter_subtitle_set = False
            i += 1
            continue

        # H2 = section heading or chapter subtitle
        if strip.startswith('## '):
            text = _strip_inline(strip[3:])
            if current is not None and not chapter_subtitle_set and not current['blocks']:
                current['subtitle'] = text
                chapter_subtitle_set = True
            elif current is not None:
                current['blocks'].append({'type': 'heading', 'text': text})
            i += 1
            continue

        # H3
        if strip.startswith('### '):
            if current is not None:
                current['blocks'].append({'type': 'heading', 'text': _strip_inline(strip[4:])})
            i += 1
            continue

        # Image
        if strip.startswith('!['):
            m = re.match(r'!\[([^\]]*)\]\(([^)]+)\)', strip)
            if m and current is not None:
                next_line = lines[i + 1] if i + 1 < len(lines) else None
                block = {'type': 'image', 'alt': m.group(1), 'url': m.group(2)}
                if next_line:
                    cap = re.match(r'^\*(.+)\*$', next_line.strip())
                    if cap:
                        block['caption'] = cap.group(1)
                        skip_next = True
                current['blocks'].append(block)
            i += 1
            continue

        # Paragraph
        if strip and current is not None:
            para = [strip]
            j = i + 1
            while j < len(lines):
                ns = lines[j].strip()
                if (not ns or ns.startswith('#') or ns.startswith('>')
                        or ns.startswith('![') or ns.startswith(':::')
                        or re.match(r'^[-*_]{3,}$', ns)):
                    break
                para.append(ns)
                j += 1
            current['blocks'].append({'type': 'paragraph', 'text': _strip_inline(' '.join(para))})
            i = j
            continue

        i += 1

    flush_quote()
    if current is not None:
        chapters.append(current)

    return meta, chapters

def md_to_chapters(path: Path) -> list[dict]:
    _, chapters = parse_markdown(path.read_text(encoding="utf-8"))
    return chapters

def epub_to_chapters(path: Path) -> list[dict]:
    try:
        from ebooklib import epub as eblib
        from html.parser import HTMLParser

        class _Extractor(HTMLParser):
            def __init__(self):
                super().__init__()
                self.result: list[str] = []
                self._skip = False
            def handle_starttag(self, tag, attrs):
                self._skip = tag in ('style', 'script')
            def handle_endtag(self, tag):
                if tag in ('p', 'h1', 'h2', 'h3', 'li'):
                    self.result.append('\n')
                self._skip = False
            def handle_data(self, data):
                if not self._skip:
                    self.result.append(data)

        book = eblib.read_epub(str(path))
        chapters, ch_num = [], 0
        for item in book.get_items_of_type(eblib.ITEM_DOCUMENT):
            raw = "".join((_x := _Extractor(), _x.feed(item.get_content().decode('utf-8', errors='replace')), _x.result)[2]).strip()
            if not raw:
                continue
            ch_num += 1
            blocks = [{"type": "paragraph", "text": p.strip()} for p in raw.split('\n\n') if p.strip()]
            chapters.append({"id": f"ch{ch_num}", "number": ch_num, "title": f"Chapter {ch_num}", "blocks": blocks})
        return chapters
    except ImportError:
        err("ebooklib not found — install: pip install ebooklib lxml")
        return []

def pdf_to_chapters(path: Path) -> list[dict]:
    try:
        import pypdf
        reader = pypdf.PdfReader(str(path))
        all_text = "\n\n".join(pg.extract_text() or "" for pg in reader.pages)
        blocks = [{"type": "paragraph", "text": p.strip()} for p in all_text.split('\n\n') if p.strip()]
        return [{"id": "ch1", "number": 1, "title": "Content", "blocks": blocks}]
    except ImportError:
        err("pypdf not found — install: pip install pypdf")
        return []

# ── HTML injection ─────────────────────────────────────────────────────────────
def inject_into_template(book_data: dict, template: Path, output: Path) -> None:
    html      = template.read_text(encoding="utf-8")
    book_json = json.dumps(book_data, ensure_ascii=False, separators=(',', ':'))

    html = re.sub(
        r'<!--@@BOOK_DATA_START@@-->.*?<!--@@BOOK_DATA_END@@-->',
        f'<!--@@BOOK_DATA_START@@-->\n    <script>window.__BOOK_DATA__ = {book_json};</script>\n    <!--@@BOOK_DATA_END@@-->',
        html, flags=re.DOTALL,
    )
    if 'window.__BOOK_DATA__ = null' in html:
        html = html.replace('window.__BOOK_DATA__ = null;', f'window.__BOOK_DATA__ = {book_json};')

    title = book_data.get("title", "Book")
    html  = re.sub(r'<title>.*?</title>', f'<title>{escape(title)}</title>', html)
    output.write_text(html, encoding="utf-8")

# ── TTS ────────────────────────────────────────────────────────────────────────
QUOTES = {"pl": ("„", "”"), "en": ("“", "”")}

def _build_tts_parts(chapter: dict, lang: str) -> list[tuple[str, dict]]:
    q_open, q_close = QUOTES.get(lang, ('"', '"'))
    parts: list[tuple[str, dict]] = []

    number   = chapter.get("number", "")
    title    = (chapter.get("title") or "").strip()
    subtitle = (chapter.get("subtitle") or "").strip()

    if isinstance(number, int):
        intro = f"Rozdział {number}." if lang == "pl" else f"Chapter {number}."
    else:
        intro = f"{number}." if number else ""

    if intro:    parts.append((intro,           {"type": "intro"}))
    if title:    parts.append((f"{title}.",     {"type": "intro"}))
    if subtitle: parts.append((f"{subtitle}.",  {"type": "intro"}))

    for bi, block in enumerate(chapter.get("blocks", [])):
        btype = block.get("type", "")
        text  = (block.get("text") or "").strip()
        if not text:
            continue
        if btype == "paragraph":
            parts.append((text, {"type": "block", "bi": bi, "part": "text"}))
        elif btype == "heading":
            parts.append((f"  {text}.", {"type": "block", "bi": bi, "part": "text"}))
        elif btype == "quote":
            parts.append((f"{q_open}{text}{q_close}", {"type": "block", "bi": bi, "part": "text"}))
            attr = (block.get("attribution") or "").strip()
            if attr:
                parts.append((f"— {attr}.", {"type": "block", "bi": bi, "part": "attr"}))
        elif btype in ("callout", "verse"):
            label = (block.get("label") or "").strip()
            if label:
                parts.append((f"{label}:", {"type": "block", "bi": bi, "part": "label"}))
            parts.append((text, {"type": "block", "bi": bi, "part": "text"}))

    return parts

def _build_word_sources(parts: list[tuple[str, dict]]) -> list[dict]:
    sources: list[dict] = []
    for text_frag, src in parts:
        for wi, _ in enumerate(text_frag.split()):
            entry = dict(src)
            if entry.get("type") == "block":
                entry["wi"] = wi
            sources.append(entry)
    return sources

def _merge_timing(timing: list[dict], sources: list[dict]) -> list[dict]:
    merged: list[dict] = []
    n = min(len(timing), len(sources))
    for i in range(n):
        entry = dict(timing[i])
        entry.update(sources[i])
        merged.append(entry)
    for i in range(n, len(timing)):
        entry = dict(timing[i])
        entry["type"] = "intro"
        merged.append(entry)
    return merged

async def _synthesize(text: str, voice: str, rate: str, pitch: str, volume: str) -> tuple[bytes, list[dict]]:
    import edge_tts
    communicate = edge_tts.Communicate(text, voice, rate=rate, pitch=pitch, volume=volume)
    audio_chunks: list[bytes] = []
    timing_events: list[dict] = []
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            audio_chunks.append(chunk["data"])
        elif chunk["type"] == "WordBoundary":
            s = round(chunk["offset"] / 10_000_000, 3)
            e = round((chunk["offset"] + chunk["duration"]) / 10_000_000, 3)
            timing_events.append({"w": chunk["text"], "s": s, "e": e})
    return b"".join(audio_chunks), timing_events

async def generate_tts(book_data: dict, book_id: str, dest: Path,
                       voice: str, rate: str, pitch: str, volume: str, lang: str) -> None:
    try:
        import edge_tts  # noqa: F401
    except ImportError:
        err("edge-tts not found — install: pip install edge-tts")
        return

    chapters = book_data.get("chapters", [])
    for i, chapter in enumerate(chapters):
        ch_id    = chapter.get("id", f"ch{i+1}")
        mp3_name = f"{book_id}-{ch_id}.mp3"
        mp3_path = dest / mp3_name

        info(f"TTS {i+1}/{len(chapters)}: {chapter.get('title','')}")
        try:
            parts   = _build_tts_parts(chapter, lang)
            sources = _build_word_sources(parts)
            full_text = " ".join(p[0] for p in parts)
            audio_bytes, timing_events = await _synthesize(full_text, voice, rate, pitch, volume)
            mp3_path.write_bytes(audio_bytes)
            merged = _merge_timing(timing_events, sources)
            if lang == 'pl':
                chapter['timing_pl'] = merged
                chapter['audio_pl']  = mp3_name
            else:
                chapter['timing_en'] = merged
                chapter['audio_en']  = mp3_name
            ok(f"Audio: {mp3_name} ({len(audio_bytes)//1024} kB, {len(merged)} words)")
        except Exception as e:
            err(f"TTS error: {e}")

# ── Export CSS (PDF-safe — no Google Fonts) ────────────────────────────────────
PDF_CSS = """
@page {
  margin: 2.5cm 3cm;
  size: A5;
}
@page cover-page {
  margin: 0;
  size: A5;
}
.cover-page {
  page: cover-page;
  page-break-after: always;
  width: 148mm;
  height: 210mm;
  overflow: hidden;
}
.cover-page img {
  display: block;
  width: 148mm;
  height: 210mm;
  object-fit: cover;
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: Georgia, 'Times New Roman', Times, serif;
  font-size: 11pt;
  line-height: 1.75;
  color: #1a1714;
  background: white;
}

.chapter {
  page-break-before: always;
  margin-bottom: 3rem;
}
.chapter:first-of-type { page-break-before: auto; }

.chapter-number {
  display: block;
  font-family: 'Courier New', Courier, monospace;
  font-size: 7pt;
  letter-spacing: 0.4em;
  text-transform: uppercase;
  color: #8a6f2e;
  margin-bottom: 0.5rem;
}
.chapter-title {
  font-size: 1.8em;
  font-weight: bold;
  font-style: italic;
  line-height: 1.15;
  color: #1a1714;
  margin-bottom: 0.35rem;
}
.chapter-subtitle {
  font-family: Helvetica, Arial, sans-serif;
  font-size: 8pt;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: #6b6257;
  margin-bottom: 1rem;
}
.chapter-rule {
  width: 36px;
  height: 1px;
  border: none;
  border-top: 1px solid rgba(138,111,46,0.4);
  margin: 1rem 0 2rem;
}

.block + .block { margin-top: 1.1em; }

.block-paragraph {
  color: #1a1714;
  font-size: 1em;
  line-height: 1.75;
  text-align: justify;
  hyphens: auto;
  -webkit-hyphens: auto;
}
.dc {
  float: left;
  font-size: 3.1em;
  line-height: 0.78;
  margin-right: 0.06em;
  margin-top: 0.04em;
  color: #8a6f2e;
  font-weight: bold;
  font-style: italic;
}
.block-paragraph.drop-cap-para {
  text-align: left;
}
.block-paragraph.indent {
  text-indent: 1.5em;
}

.block-heading {
  font-family: 'Courier New', Courier, monospace;
  font-size: 7pt;
  font-weight: bold;
  letter-spacing: 0.3em;
  text-transform: uppercase;
  color: #8a6f2e;
  margin-top: 2.5rem;
  padding-top: 1.25rem;
  border-top: 1px solid rgba(138,111,46,0.3);
  page-break-after: avoid;
}

.block-quote {
  border-left: 2px solid rgba(138,111,46,0.4);
  padding: 0.75rem 1.1rem;
  background: rgba(138,111,46,0.05);
  page-break-inside: avoid;
}
.block-quote-text { font-style: italic; font-size: 1.02em; line-height: 1.7; }
.block-quote-attr {
  display: block;
  font-family: Helvetica, Arial, sans-serif;
  font-size: 8pt;
  letter-spacing: 0.1em;
  color: #8a6f2e;
  text-transform: uppercase;
  margin-top: 0.4rem;
}

.block-divider {
  text-align: center;
  font-size: 10pt;
  color: #6b6257;
  letter-spacing: 0.3em;
  padding: 0.5rem 0;
}

.block-callout {
  border-left: 2px solid #4a6fa5;
  padding: 0.8rem 1rem;
  background: rgba(74,111,165,0.05);
  page-break-inside: avoid;
}
.block-callout-label {
  font-family: 'Courier New', Courier, monospace;
  font-size: 7pt;
  letter-spacing: 0.25em;
  color: #4a6fa5;
  text-transform: uppercase;
  margin-bottom: 0.35rem;
}
.block-callout-text { font-size: 0.94em; line-height: 1.7; }

.block-verse {
  font-style: italic;
  white-space: pre-wrap;
  color: #6b6257;
  line-height: 1.9;
  padding-left: 1.5rem;
  border-left: 1px solid rgba(120,105,80,0.25);
}

figure { margin: 1.5rem 0; page-break-inside: avoid; }
figure img { width: 100%; display: block; }
figcaption {
  margin-top: 0.4rem;
  font-family: Helvetica, Arial, sans-serif;
  font-size: 8pt;
  letter-spacing: 0.08em;
  color: #6b6257;
  text-align: center;
}
"""

def _block_to_html(block: dict, idx: int, prev_type: str | None) -> str:
    btype = block.get("type", "")
    raw   = block.get("text") or ""
    text  = escape(raw)

    if btype == "paragraph":
        cls = "block block-paragraph"
        if idx == 0 and raw:
            first = escape(raw[0])
            rest  = escape(raw[1:])
            text  = f'<span class="dc">{first}</span>{rest}'
            cls  += " drop-cap-para"
        elif prev_type == "paragraph":
            cls += " indent"
        return f'<p class="{cls}">{text}</p>'

    if btype == "heading":
        return f'<h2 class="block block-heading">{text}</h2>'

    if btype == "quote":
        attr = block.get("attribution") or ""
        attr_html = f'<cite class="block-quote-attr">— {escape(attr)}</cite>' if attr else ""
        return (f'<blockquote class="block block-quote">'
                f'<p class="block-quote-text">{text}</p>{attr_html}'
                f'</blockquote>')

    if btype == "divider":
        return '<div class="block block-divider">✦ ✦ ✦</div>'

    if btype == "callout":
        label = block.get("label") or ""
        label_html = f'<div class="block-callout-label">{escape(label)}</div>' if label else ""
        return (f'<div class="block block-callout">'
                f'{label_html}<p class="block-callout-text">{text}</p></div>')

    if btype == "verse":
        return f'<pre class="block block-verse">{text}</pre>'

    if btype == "image":
        url = escape(block.get("url") or "")
        alt = escape(block.get("alt") or "")
        cap = block.get("caption") or ""
        cap_html = f'<figcaption>{escape(cap)}</figcaption>' if cap else ""
        return f'<figure><img src="{url}" alt="{alt}"/>{cap_html}</figure>'

    return ""

def _chapter_to_html(chapter: dict, lang: str) -> str:
    num      = chapter.get("number", "")
    title    = chapter.get("title", "")
    subtitle = chapter.get("subtitle", "")
    blocks   = chapter.get("blocks", [])

    num_label = (f"Rozdział {num}" if lang == "pl" else f"Chapter {num}") if isinstance(num, int) else str(num)
    sub_html  = f'<p class="chapter-subtitle">{escape(subtitle)}</p>' if subtitle else ""

    header = (f'<span class="chapter-number">{escape(num_label)}</span>\n'
              f'<h1 class="chapter-title">{escape(title)}</h1>\n'
              f'{sub_html}\n'
              f'<hr class="chapter-rule"/>\n')

    parts = [header]
    prev_type: str | None = None
    for i, block in enumerate(blocks):
        h = _block_to_html(block, i, prev_type)
        if h:
            parts.append(h)
        btype = block.get("type", "")
        if btype not in ("divider", "image"):
            prev_type = btype

    return "\n".join(parts)

def _book_to_html(book: dict) -> str:
    title    = book.get("title", "Book")
    author   = book.get("author", "")
    subtitle = book.get("subtitle", "")
    lang     = book.get("lang", "en")
    chapters = book.get("chapters", [])
    cover    = book.get("cover", "")

    cover_page_html = ""
    if cover and cover.startswith("data:"):
        cover_page_html = f'<div class="cover-page"><img src="{cover}" alt="Cover"/></div>'

    author_html   = f'<p class="book-author">{escape(author)}</p>' if author else ''
    subtitle_html = f'<p class="book-subtitle">{escape(subtitle)}</p>' if subtitle else ''
    header_html = (
        f'<header class="book-header">\n'
        f'  {author_html}\n'
        f'  <h1 class="book-title">{escape(title)}</h1>\n'
        f'  {subtitle_html}\n'
        f'</header>'
    )

    chapters_html = "\n\n".join(
        f'<section class="chapter" id="ch-{ch.get("id","")}">\n'
        f'{_chapter_to_html(ch, lang)}\n'
        f'</section>'
        for ch in chapters
    )

    return f"""<!DOCTYPE html>
<html lang="{escape(lang)}">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{escape(title)}</title>
  <style>{PDF_CSS}
.book-header {{
  text-align: center;
  padding: 3rem 0 4rem;
  border-bottom: 1px solid rgba(138,111,46,0.3);
  margin-bottom: 3rem;
  page-break-after: always;
}}
.book-author {{
  font-family: 'Courier New', monospace;
  font-size: 7pt;
  letter-spacing: 0.4em;
  text-transform: uppercase;
  color: #8a6f2e;
  margin-bottom: 0.75rem;
}}
.book-title {{
  font-size: 2.2em;
  font-weight: bold;
  font-style: italic;
  color: #1a1714;
}}
.book-subtitle {{
  font-family: Helvetica, Arial, sans-serif;
  font-size: 8pt;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: #6b6257;
  margin-top: 0.5rem;
}}
  </style>
</head>
<body>
  {cover_page_html}
  {header_html}
  {chapters_html}
</body>
</html>"""

# ── EPUB export ────────────────────────────────────────────────────────────────
def make_epub(book: dict, output: Path) -> None:
    try:
        from ebooklib import epub
    except ImportError:
        err("ebooklib not found — install: pip install ebooklib lxml")
        return

    title    = book.get("title", "Book")
    author   = book.get("author", "Unknown")
    lang     = book.get("lang", "en")
    book_id  = book.get("id", "book")
    chapters = book.get("chapters", [])

    ebook = epub.EpubBook()
    ebook.set_identifier(book_id)
    ebook.set_title(title)
    ebook.set_language(lang)
    if author:
        ebook.add_author(author)

    # Cover
    cover_raw = book.get("cover", "")
    if cover_raw and cover_raw.startswith("data:"):
        try:
            mime, b64 = cover_raw.split(";base64,", 1)
            mime = mime.split(":", 1)[1]
            ext  = "jpg" if "jpeg" in mime else "png"
            ebook.set_cover(f"cover.{ext}", base64.b64decode(b64))
        except Exception:
            pass

    css_item = epub.EpubItem(uid="style", file_name="style.css",
                              media_type="text/css", content=PDF_CSS.encode("utf-8"))
    ebook.add_item(css_item)

    spine, toc_list = ["nav"], []
    for ch in chapters:
        ch_id    = str(ch.get("id", "ch"))
        ch_title = ch.get("title", "")
        fname    = f"chapter_{ch_id}.xhtml"
        body_html = _chapter_to_html(ch, lang)
        content   = (
            '<?xml version="1.0" encoding="utf-8"?>'
            '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">'
            f'<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{lang}">'
            f'<head><title>{escape(ch_title)}</title>'
            f'<link rel="stylesheet" type="text/css" href="style.css"/>'
            f'</head><body><div class="chapter">{body_html}</div></body></html>'
        )
        epub_ch = epub.EpubHtml(title=ch_title, file_name=fname, lang=lang)
        epub_ch.content = content.encode("utf-8")
        epub_ch.add_item(css_item)
        ebook.add_item(epub_ch)
        spine.append(epub_ch)
        toc_list.append(epub.Link(fname, ch_title, ch_id))

    ebook.toc   = toc_list
    ebook.spine = spine
    ebook.add_item(epub.EpubNcx())
    ebook.add_item(epub.EpubNav())
    epub.write_epub(str(output), ebook)
    ok(f"EPUB: {output.name} ({output.stat().st_size // 1024} kB)")

# ── PDF export ─────────────────────────────────────────────────────────────────
def make_pdf(book: dict, output: Path) -> None:
    html_content = _book_to_html(book)
    tmp_html = output.with_suffix(".tmp.html")
    tmp_html.write_text(html_content, encoding="utf-8")

    try:
        from weasyprint import HTML as WP_HTML
        WP_HTML(filename=str(tmp_html)).write_pdf(str(output))
        tmp_html.unlink(missing_ok=True)
        ok(f"PDF: {output.name} ({output.stat().st_size // 1024} kB)")
    except ImportError:
        # Rename to print-ready HTML
        print_html = output.with_suffix(".print.html")
        tmp_html.rename(print_html)
        info(f"weasyprint not installed — saved print HTML: {print_html.name}")
        info("Open in browser and use Ctrl+P → Save as PDF")
        info("Install: pip install weasyprint")
    except Exception as e:
        tmp_html.unlink(missing_ok=True)
        err(f"PDF error: {e}")

# ── Load book source ───────────────────────────────────────────────────────────
def load_book_source(book_dir: Path) -> dict:
    config = load_config(book_dir)
    cover  = load_cover_b64(book_dir)

    md_path   = book_dir / "book.md"
    epub_path = book_dir / "book.epub"
    pdf_path  = book_dir / "book.pdf"

    if md_path.exists():
        info(f"Source: {md_path.name}")
        chapters = md_to_chapters(md_path)
    elif epub_path.exists():
        info(f"Source: {epub_path.name}")
        chapters = epub_to_chapters(epub_path)
    elif pdf_path.exists():
        info(f"Source: {pdf_path.name}")
        chapters = pdf_to_chapters(pdf_path)
    else:
        raise FileNotFoundError("No content file found: book.md / book.epub / book.pdf")

    return {**config, "cover": cover, "chapters": chapters}

# ── Generate a single book ─────────────────────────────────────────────────────
def generate_book(
    book_dir: Path,
    do_tts: bool   = True,
    do_epub: bool  = True,
    do_pdf: bool   = True,
    tts_voice: str = "",
    tts_rate: str  = "+0%",
    tts_pitch: str = "+0Hz",
    tts_volume: str = "+0%",
) -> bool:
    book_id  = book_dir.name
    dest_dir = BOOK_DEST / book_id
    dest_dir.mkdir(parents=True, exist_ok=True)

    print()
    print(f"  {gold(bold('★ ATLAS BOOKS — GENERATING'))}: {bold(book_id)}")
    print(f"  {dim('source: ' + str(book_dir))}")
    print(f"  {dim('dest:   ' + str(dest_dir))}")

    # 1. Load source
    step("Loading source")
    try:
        book_data = load_book_source(book_dir)
        lang      = book_data.get('lang', 'pl')
        ok(f"Title: {book_data.get('title','')} · {len(book_data.get('chapters',[]))} chapters")
    except Exception as e:
        err(str(e))
        return False

    # 2. TTS audio
    if do_tts:
        step("Generating TTS audio")
        tts_cfg = book_data.get('tts', {})
        voice   = tts_voice or tts_cfg.get('voice', 'pl-PL-MarekNeural' if lang == 'pl' else 'en-US-AriaNeural')
        rate    = tts_rate  or tts_cfg.get('rate',  '+0%')
        pitch   = tts_pitch or tts_cfg.get('pitch', '+0Hz')
        info(f"Voice: {voice}  Rate: {rate}  Pitch: {pitch}")
        asyncio.run(generate_tts(
            book_data, book_id, dest_dir,
            voice=voice, rate=rate, pitch=pitch, volume=tts_volume, lang=lang,
        ))

    # 3. Build HTML viewer
    step("Building HTML viewer")
    if not TEMPLATE_PATH.exists():
        err(f"Template not found: {TEMPLATE_PATH}")
        err("Run: npm run build-viewer   (builds public/book-template.html)")
        return False

    out_html = dest_dir / f"{book_id}.html"
    inject_into_template(book_data, TEMPLATE_PATH, out_html)
    ok(f"HTML: {out_html.name} ({out_html.stat().st_size // 1024} kB)")

    # 4. EPUB
    if do_epub:
        step("Building EPUB")
        make_epub(book_data, dest_dir / f"{book_id}.epub")

    # 5. PDF
    if do_pdf:
        step("Building PDF")
        make_pdf(book_data, dest_dir / f"{book_id}.pdf")

    print()
    ok(f"Done → {dest_dir}")
    print()
    return True

# ── List books ─────────────────────────────────────────────────────────────────
def list_books() -> None:
    print(f"\n  {gold(bold('Atlas Books — Source Books'))}  ({BOOK_SOURCE})\n")
    if not BOOK_SOURCE.exists():
        err(f"books-source/ not found: {BOOK_SOURCE}"); return
    for d in sorted(BOOK_SOURCE.iterdir()):
        if not d.is_dir():
            continue
        cfg_path = d / "config.json"
        if not cfg_path.exists():
            print(f"  {dim('○')} {d.name}  {gray('(no config.json)')}")
            continue
        try:
            cfg = json.loads(cfg_path.read_text())
        except Exception:
            print(f"  {dim('○')} {d.name}  {gray('(invalid config.json)')}"); continue

        title   = cfg.get('title', d.name)
        author  = cfg.get('author', '')
        sources = [f.suffix[1:] for f in [d/'book.md', d/'book.epub', d/'book.pdf'] if f.exists()]
        cover   = any((d/n).exists() for n in COVER_NAMES)
        pub     = cfg.get('published', False)
        pub_dt  = cfg.get('published_date', None)
        dest_ok = (BOOK_DEST / d.name / f"{d.name}.html").exists()

        pub_label = (
            f"{green('published')} {gray(pub_dt)}" if pub and pub_dt
            else (green('published') if pub else gray('draft'))
        )
        print(f"  {gold('►')} {bold(d.name)}")
        print(f"    {dim(title)}{' · ' + dim(author) if author else ''}")
        print(f"    source: {gray(', '.join(sources) or 'missing!')}  "
              f"cover: {'yes' if cover else gray('no')}  "
              f"generated: {'yes' if dest_ok else gray('no')}  "
              f"status: {pub_label}")
    print()

# ── Main ───────────────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--input",       "-i", default=None, metavar="NAME_OR_PATH")
    parser.add_argument("--all",         action="store_true", help="Generate all books in books-source/")
    parser.add_argument("--list",        action="store_true")
    parser.add_argument("--no-epub",     action="store_true", help="Skip EPUB generation")
    parser.add_argument("--no-pdf",      action="store_true", help="Skip PDF generation")
    parser.add_argument("--no-tts",      action="store_true", help="Skip MP3 audio generation")
    parser.add_argument("--tts-voice",   default="")
    parser.add_argument("--tts-rate",    default="+0%")
    parser.add_argument("--tts-pitch",   default="+0Hz")
    parser.add_argument("--tts-volume",  default="+0%")
    parser.add_argument("-h", "--help",  action="store_true")
    args = parser.parse_args()

    if args.help:
        print_help(); sys.exit(0)
    if args.list:
        list_books(); sys.exit(0)

    do_tts  = not args.no_tts
    do_epub = not args.no_epub
    do_pdf  = not args.no_pdf
    tts_kwargs = dict(
        do_tts=do_tts, do_epub=do_epub, do_pdf=do_pdf,
        tts_voice=args.tts_voice, tts_rate=args.tts_rate,
        tts_pitch=args.tts_pitch, tts_volume=args.tts_volume,
    )

    if args.all:
        if not BOOK_SOURCE.exists():
            err(f"books-source/ not found: {BOOK_SOURCE}"); sys.exit(1)
        books = [d for d in sorted(BOOK_SOURCE.iterdir())
                 if d.is_dir() and (d / "config.json").exists()]
        if not books:
            err("No books found in books-source/"); sys.exit(1)
        success = all(generate_book(b, **tts_kwargs) for b in books)
        sys.exit(0 if success else 1)

    if not args.input:
        # Default: generate all books
        if not BOOK_SOURCE.exists():
            err(f"books-source/ not found: {BOOK_SOURCE}"); sys.exit(1)
        books = [d for d in sorted(BOOK_SOURCE.iterdir())
                 if d.is_dir() and (d / "config.json").exists()]
        if not books:
            err("No books found in books-source/"); sys.exit(1)
        success = all(generate_book(b, **tts_kwargs) for b in books)
        sys.exit(0 if success else 1)

    # Resolve input: name or path
    inp = Path(args.input)
    if inp.is_dir():
        book_dir = inp.resolve()
    elif (BOOK_SOURCE / args.input).is_dir():
        book_dir = (BOOK_SOURCE / args.input).resolve()
    else:
        err(f"Book not found: '{args.input}'  (looked in books-source/ and as a path)"); sys.exit(1)

    ok_result = generate_book(book_dir, **tts_kwargs)
    sys.exit(0 if ok_result else 1)


if __name__ == "__main__":
    main()
